version: "3.8"

services:
  app:
    build: .
    container_name: postgres_cloud_app
    env_file:
      - .env
    ports:
      - "420:420"
    volumes:
      - ./data:/var/lib/postgresql/data
    depends_on:
      - postgres
      - pgadmin
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - app_network
    security_opt:
      - no-new-privileges:true
    user: "1000:1000" # Run as non-root user

  postgres:
    image: postgres:13-alpine
    container_name: postgres_container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app_network
    security_opt:
      - no-new-privileges:true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - app_network
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
